source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'erubis'
gem 'faraday'
gem 'faraday_middleware'
gem 'oj'
gem 'oj_mimic_json'
gem 'dotenv'
gem 'activesupport', require: 'active_support/all'
gem 'activerecord'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'sqlite3'
gem 'pry', group: :development
